import './globals.css'
import type { Metadata } from 'next'
import { Cairo } from 'next/font/google'
import CartProvider from '@/providers/CartProvider'
import { Toaster } from 'react-hot-toast'

const cairo = Cairo({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Al-Rafidain Store',
  description: 'Generated by student: hussein ahmed',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body className={`${cairo.className} text-slate-600`}>
        <Toaster position="bottom-right" 
                  reverseOrder={false}/>
        <CartProvider>
          <section className='flex flex-col min-h-screen'>
            <main className='flex-grow'>{children}</main>
          </section>
        </CartProvider>
      </body>
    </html>
  )
}
